name: deploy-lilgobguides

on:
    workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install npm packages
        working-directory: .
        run: npm install
      - name: Build Bootstrap CSS
        working-directory: .
        run: npm run build-bootstrap-css
      - name: show node_modules/bootstrap files
        working-directory: .
        run: |
          echo "→ node_modules/bootstrap/dist/js:"
          ls -l node_modules/bootstrap/dist/js || echo "(not found)"
      - name: show existing wwwroot/js
        working-directory: .
        run: |
          echo "→ before copy, wwwroot/js contains:"
          ls -l wwwroot/js || echo "(empty or folder missing)"
      - name: Build Bootstrap JS
        working-directory: .
        run: npm run build-bootstrap-js
      - name: verify copy succeeded
        working-directory: .
        run: |
          echo "→ after copy, wwwroot/js contains:"
          ls -l wwwroot/js || echo "(still empty)"
      - name: Publish self-contained executable
        run: dotnet publish . -r linux-arm64 --self-contained true
      - name: SCP dotnet executable to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          source: "./bin/Release/net8.0/linux-arm64/publish"
          target: ${{ secrets.lilgobguides_DEPLOY_DIRECTORY }}